
export const ACTION_TYPES =  {
  REQUEST_USER_LOGIN: "REQUEST_USER_LOGIN",
  USER_LOGIN_SUCCESSFUL: "USER_LOGIN_SUCCESSFUL",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  LOAD_USER: "LOAD_USER",
  REQUEST_USER_LOGOUT: "REQUEST_USER_LOGOUT",
  USER_LOGOUT_SUCCESSFUL: "USER_LOGOUT_SUCCESSFUL",
  IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",

  MENU_LOAD_ALL_REQUEST: "MENU_LOAD_ALL_REQUEST",
  MENU_LOAD_ALL: "MENU_LOAD_ALL"
};
