
export const ACTION_TYPES =  {
  REQUEST_USER_LOGIN: "REQUEST_USER_LOGIN",
  USER_LOGIN_SUCCESSFUL: "USER_LOGIN_SUCCESSFUL",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  LOAD_USER: "LOAD_USER",
  LOGOUT_USER: "LOGOUT_USER"
};
